region          = "ap-south-1"
vpc_name        = "ansible-vpc"
vpc_cidr        = "10.0.0.0/16"
ami             = "ami-00305d2fa3c93abfc"
key_name        = "ansible-playbooks"
my-windows-keys = "ansible-playbooks"
instance_type   = "t2.micro"